# Project information
site_name: 'eBGF'
site_description: 'eco Blockchain Governance Framework'
site_author: 'if(is)'
site_url: 'https://internet-sicherheit.github.io/eBGF/'

# Repository
repo_name: 'eBGF'
repo_url: 'https://github.com/internet-sicherheit/eBGF'
edit_uri: 'https://github.com/internet-sicherheit/eBGF/edit/main/docs'

#Site navigation
nav:

   - Home: 
        - eBGF Overview: index.md
        - Project initiators: about.md
        - News: news.md

   - Framework:
        - Scope:
            - Introduction: framework/0-scope/introduction.md
            - Scope: framework/0-scope/scope.md
        - Organisation: 
            - Introduction: framework/1-organisation/Organisation.md
            - Motivation: framework/1-organisation/RFC-0111.md
            - Goals: framework/1-organisation/RFC-0121.md
            - Values: framework/1-organisation/RFC-0131.md
            - Accountability: framework/1-organisation/RFC-0141.md
            - Permission-Policy: framework/1/RFC-0151.md
        - Membership: 
            - Introduction: framework/4-membership/Membership.md
            - Onboarding: framework/4-membership/RFC-0411.md
            - Offboarding: framework/4-membership/RFC-0421.md
        - Collaboration: 
            - Introduction: framework/6-collaboration/Collaboration.md
            - Communication: framework/6/RFC-0611.md
            - Decision-making: framework/6/RFC-0621.md
            - Onchain/offchain: framework/6/RFC-0631.md
        - Economics: 
            - Introduction: framework/7-economics/Economics.md
            - Incentives: framework/7-economics/RFC-0711.md
            - Fees: framework/7-economics/RFC-0721.md
        - Regulation: 
            - Introduction: framework/3-regulation/Regulation.md
            - Antitrust: framework/3-regulation/RFC-0311.md
            - AML and KYC: framework/3-regulation/RFC-0321.md
            - Privacy (GDPR): framework/3-regulation/RFC-0331.md
            - Copyright (DMS): framework/3-regulation/RFC-0341.md
            - Services (DSA): framework/3-regulation/RFC-0351.md
        - Standards: 
            - Introduction: framework/9-standards/Standards.md
            - Identifiers: framework/9-standards/RFC-0911.md
            - Development: framework/9-standards/RFC-0921.md
        - Applications: 
            - Introduction: framework/2-applications/Applications.md
            - Use Cases: framework/2-applications/RFC-0211.md
            - App developers: framework/2-applications/RFC-0221.md
            - Business models: framework/2-applications/RFC-0231.md
            - Users: framework/2-applications/RFC-0241.md
        - Ecosystem: 
            - Introduction: framework/5-ecosystem/Ecosystem.md
            - SDK: framework/5-ecosystem/RFC-0511.md
            - Documentations: framework/5-ecosystem/RFC-0521.md
        - Maintenance: 
            - Introduction: framework/8-maintenance/Maintenance.md
            - Risk management: framework/8-maintenance/RFC-0811.md
            - Monitoring: framework/8-maintenance/RFC-0821.md
        - Protocol: 
            - Introduction: framework/10-protocol/Protocol.md
            - Concensus: framework/10-protocol/RFC-1011.md
            - Security: framework/10-protocol/RFC-1021.md
            - Hardware: framework/10-protocol/RFC-1031.md
            - Interoperability: framework/10-protocol/RFC-1041.md
            - Permissions: 
                - Introduction: framework/10-protocol/permissions.md
                - Ledger Read Permissions: framework/10-protocol/RFC-0036.md
                - Ledger Write Permissions: framework/10-protocol/RFC-0035.md
            - Scalability: framework/10-protocol/RFC-1061.md
            - Automated verification of node compliance: framework/10-protocol/RFC-0016.md
            - Technical interoperability with other networks: framework/10-protocol/RFC-0020.md
            - Protocol updates: framework/10-protocol/RFC-0037.md
            - Different node types and classes: framework/10-protocol/RFC-0007.md
        - Glossar: framework/glossar.md
        - References: framework/references.md

   - FAQ:
        - FAQ: faq.md
        - + Ask a new question: contact.md


   - Contact:
        - Contact us: contact.md

#Design
theme:
  name: material
  custom_dir: overrides
  logo: 'https://raw.githubusercontent.com/internet-sicherheit/eBGF/gh-pages/assets/images/EBGF-logo-transparent-white.png'
  favicon: 'https://raw.githubusercontent.com/internet-sicherheit/eBGF/gh-pages/assets/images/EBGF-logo-transparent-white.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/internet-sicherheit/eBGF
      name: eBGF on GitHub

markdown_extensions:
  - attr_list

#Footer
copyright: Site created by the Institute for Internet-Security - if(is). <a href="https://www.internet-sicherheit.de/impressum.html">Imprint</a>. <a href="https://www.internet-sicherheit.de/datenschutz.html">Privacy</a>. Copyright Â© 2021 <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA-4.0</a>.
